version: '3.8'

services:
  node0:
    container_name: gokite-chain-node
    image: ghcr.io/zettablock/gokite-chain:latest
    volumes:
      - ./data:/data
    user: "${CURRENT_UID}:${CURRENT_GID}"
    ports:
      - 9650:9650
      - 9651:9651
    environment:
      - AVALANCHEGO_CHAIN_CONFIG_DIR=/config
      - AVALANCHEGO_NETWORK_ID=fuji
      - AVALANCHEGO_DATA_DIR=/data
      - AVALANCHEGO_PLUGIN_DIR=/plugins/ 
      - AVALANCHEGO_HTTP_PORT=9650
      - AVALANCHEGO_STAKING_PORT=9651
      - AVALANCHEGO_TRACK_SUBNETS=vPhfFM5uUhRreVYCvnELNZFrbKLV7Gi2eNSDF66G9csDHxvG2
      - AVALANCHEGO_HTTP_ALLOWED_HOSTS=*
      - AVALANCHEGO_HTTP_HOST=0.0.0.0
      - AVALANCHEGO_PUBLIC_IP_RESOLUTION_SERVICE=ifconfigme
      - AVALANCHEGO_PARTIAL_SYNC_PRIMARY_NETWORK=true